import crafttweaker.oredict.IOreDictEntry;


val uranium = <ore:ingotUranium>;
val thorium = <ore:ingotThorium>;
val iridiumAlloy = <ore:ingotIridiumAlloy>;
val mixedMetal = <ore:ingotMixedMetal>;
val advancedAlloy = <ore:ingotAdvancedAlloy>;
val refinedIron = <ore:ingotRefinedIron>;
val zinc = <ore:ingotZinc>;
val tungstensteel = <ore:ingotTungstensteel>;
val plutonium = <ore:ingotPlutonium>;
val hotTungstensteel = <ore:ingotHotTungstensteel>;
val tungsten = <ore:ingotTungsten>;
val titanium = <ore:ingotTitanium>;
val tin = <ore:ingotTin>;
val steel = <ore:ingotSteel>;
val silver = <ore:ingotSilver>;
val platinum = <ore:ingotPlatinum>;
val nickel = <ore:ingotNickel>;
val lead = <ore:ingotLead>;
val iridium = <ore:ingotIridium>;
val invar = <ore:ingotInvar>;
val electrum = <ore:ingotElectrum>;
val copper = <ore:ingotCopper>;
val chrome = <ore:ingotChrome>;
val bronze = <ore:ingotBronze>;
val brass = <ore:ingotBrass>;
val aluminium = <ore:ingotAluminum>;

uranium.remove(<techreborn:ingot:24>);
thorium.remove(<techreborn:ingot:23>);
iridiumAlloy.remove(<techreborn:ingot:22>);
mixedMetal.remove(<techreborn:ingot:21>);
advancedAlloy.remove(<techreborn:ingot:20>);
refinedIron.remove(<techreborn:ingot:19>);
zinc.remove(<techreborn:ingot:18>);
tungstensteel.remove(<techreborn:ingot:17>);
plutonium.remove(<techreborn:ingot:25>);
hotTungstensteel.remove(<techreborn:ingot:16>);
tungsten.remove(<techreborn:ingot:15>);
titanium.remove(<techreborn:ingot:14>);
tin.remove(<techreborn:ingot:13>);
steel.remove(<techreborn:ingot:12>);
silver.remove(<techreborn:ingot:11>);
platinum.remove(<techreborn:ingot:10>);
nickel.remove(<techreborn:ingot:9>);
lead.remove(<techreborn:ingot:8>);
iridium.remove(<techreborn:ingot:7>);
invar.remove(<techreborn:ingot:6>);
electrum.remove(<techreborn:ingot:5>);
copper.remove(<techreborn:ingot:4>);
chrome.remove(<techreborn:ingot:3>);
bronze.remove(<techreborn:ingot:2>);
brass.remove(<techreborn:ingot:1>);
aluminium.remove(<techreborn:ingot>);

mods.jei.JEI.removeAndHide(<techreborn:ingot:24>);
mods.jei.JEI.removeAndHide(<techreborn:ingot:23>);
mods.jei.JEI.removeAndHide(<techreborn:ingot:22>);
mods.jei.JEI.removeAndHide(<techreborn:ingot:21>);
mods.jei.JEI.removeAndHide(<techreborn:ingot:20>);
mods.jei.JEI.removeAndHide(<techreborn:ingot:19>);
mods.jei.JEI.removeAndHide(<techreborn:ingot:18>);
mods.jei.JEI.removeAndHide(<techreborn:ingot:17>);
mods.jei.JEI.removeAndHide(<techreborn:ingot:25>);
mods.jei.JEI.removeAndHide(<techreborn:ingot:16>);
mods.jei.JEI.removeAndHide(<techreborn:ingot:15>);
mods.jei.JEI.removeAndHide(<techreborn:ingot:14>);
mods.jei.JEI.removeAndHide(<techreborn:ingot:13>);
mods.jei.JEI.removeAndHide(<techreborn:ingot:12>);
mods.jei.JEI.removeAndHide(<techreborn:ingot:11>);
mods.jei.JEI.removeAndHide(<techreborn:ingot:10>);
mods.jei.JEI.removeAndHide(<techreborn:ingot:9>);
mods.jei.JEI.removeAndHide(<techreborn:ingot:8>);
mods.jei.JEI.removeAndHide(<techreborn:ingot:7>);
mods.jei.JEI.removeAndHide(<techreborn:ingot:6>);
mods.jei.JEI.removeAndHide(<techreborn:ingot:5>);
mods.jei.JEI.removeAndHide(<techreborn:ingot:4>);
mods.jei.JEI.removeAndHide(<techreborn:ingot:3>);
mods.jei.JEI.removeAndHide(<techreborn:ingot:2>);
mods.jei.JEI.removeAndHide(<techreborn:ingot:1>);
mods.jei.JEI.removeAndHide(<techreborn:ingot>);


val iridiumNug = <ore:nuggetIridium>;
val invarNug = <ore:nuggetInvar>;
val electrumNug = <ore:nuggetElectrum>;
val copperNug = <ore:nuggetCopper>;
val chromeNug = <ore:nuggetChrome>;
val bronzeNug = <ore:nuggetBronze>;
val brassNug = <ore:nuggetBrass>;
val aluminiumNug = <ore:nuggetAluminum>;
val hotTungstensteelNug = <ore:nuggetHotTungstensteel>;
val tungstenNug = <ore:nuggetTungsten>;
val titaniumNug = <ore:nuggetTitanium>;
val tinNug = <ore:nuggetTin>;
val steelNug = <ore:nuggetSteel>;
val silverNug = <ore:nuggetSilver>;
val platinumNug = <ore:nuggetPlatinum>;
val nickelNug = <ore:nuggetNickel>;
val leadNug = <ore:nuggetLead>;
val diamondNug = <ore:nuggetDiamond>;
val ironNug = <ore:nuggetIron>;
val refinedIronNug = <ore:nuggetRefinedIron>;
val zincNug = <ore:nuggetZinc>;
val tungstensteelNug = <ore:nuggetTungstensteel>;

iridiumNug.remove(<techreborn:nuggets:7>);
invarNug.remove(<techreborn:nuggets:6>);
electrumNug.remove(<techreborn:nuggets:5>);
copperNug.remove(<techreborn:nuggets:4>);
chromeNug.remove(<techreborn:nuggets:3>);
bronzeNug.remove(<techreborn:nuggets:2>);
brassNug.remove(<techreborn:nuggets:1>);
aluminiumNug.remove(<techreborn:nuggets>);
hotTungstensteelNug.remove(<techreborn:nuggets:16>);
tungstenNug.remove(<techreborn:nuggets:15>);
titaniumNug.remove(<techreborn:nuggets:14>);
tinNug.remove(<techreborn:nuggets:13>);
steelNug.remove(<techreborn:nuggets:12>);
silverNug.remove(<techreborn:nuggets:11>);
platinumNug.remove(<techreborn:nuggets:10>);
nickelNug.remove(<techreborn:nuggets:9>);
leadNug.remove(<techreborn:nuggets:8>);
diamondNug.remove(<techreborn:nuggets:24>);
ironNug.remove(<techreborn:nuggets:23>);
refinedIronNug.remove(<techreborn:nuggets:19>);
zincNug.remove(<techreborn:nuggets:18>);
tungstensteelNug.remove(<techreborn:nuggets:17>);

mods.jei.JEI.removeAndHide(<techreborn:nuggets:7>);
mods.jei.JEI.removeAndHide(<techreborn:nuggets:6>);
mods.jei.JEI.removeAndHide(<techreborn:nuggets:5>);
mods.jei.JEI.removeAndHide(<techreborn:nuggets:4>);
mods.jei.JEI.removeAndHide(<techreborn:nuggets:3>);
mods.jei.JEI.removeAndHide(<techreborn:nuggets:2>);
mods.jei.JEI.removeAndHide(<techreborn:nuggets:1>);
mods.jei.JEI.removeAndHide(<techreborn:nuggets>);
mods.jei.JEI.removeAndHide(<techreborn:nuggets:16>);
mods.jei.JEI.removeAndHide(<techreborn:nuggets:15>);
mods.jei.JEI.removeAndHide(<techreborn:nuggets:14>);
mods.jei.JEI.removeAndHide(<techreborn:nuggets:13>);
mods.jei.JEI.removeAndHide(<techreborn:nuggets:12>);
mods.jei.JEI.removeAndHide(<techreborn:nuggets:11>);
mods.jei.JEI.removeAndHide(<techreborn:nuggets:10>);
mods.jei.JEI.removeAndHide(<techreborn:nuggets:9>);
mods.jei.JEI.removeAndHide(<techreborn:nuggets:8>);
mods.jei.JEI.removeAndHide(<techreborn:nuggets:24>);
mods.jei.JEI.removeAndHide(<techreborn:nuggets:23>);
mods.jei.JEI.removeAndHide(<techreborn:nuggets:19>);
mods.jei.JEI.removeAndHide(<techreborn:nuggets:18>);
mods.jei.JEI.removeAndHide(<techreborn:nuggets:17>);


val yellowGarnet = <ore:gemYellowGarnet>;
val redGarnet = <ore:gemRedGarnet>;
val peridot = <ore:gemPeridot>;
val sapphire = <ore:gemSapphire>;
val ruby = <ore:gemRuby>;

yellowGarnet.remove(<techreborn:gem:4>);
redGarnet.remove(<techreborn:gem:3>);
peridot.remove(<techreborn:gem:2>);
sapphire.remove(<techreborn:gem:1>);
ruby.remove(<techreborn:gem>);

mods.jei.JEI.removeAndHide(<techreborn:gem:4>);
mods.jei.JEI.removeAndHide(<techreborn:gem:3>);
mods.jei.JEI.removeAndHide(<techreborn:gem:2>);
mods.jei.JEI.removeAndHide(<techreborn:gem:1>);
mods.jei.JEI.removeAndHide(<techreborn:gem>);


val ironPlate = <ore:plateIron>;
val goldPlate = <ore:plateGold>;
val carbonPlate = <ore:plateCarbon>;
val redstonePlate = <ore:plateRedstone>;
val diamondPlate = <ore:plateDiamond>;
val emeraldPlate = <ore:plateEmerald>;
val coalPlate = <ore:plateCoal>;
val obsidianPlate = <ore:plateObsidian>;
val lazuritePlate = <ore:plateLazurite>;
val siliconPlate = <ore:plateSilicon>;

ironPlate.remove(<techreborn:plates>);
goldPlate.remove(<techreborn:plates:1>);
carbonPlate.remove(<techreborn:plates:2>);
redstonePlate.remove(<techreborn:plates:4>);
diamondPlate.remove(<techreborn:plates:5>);
emeraldPlate.remove(<techreborn:plates:6>);
coalPlate.remove(<techreborn:plates:8>);
obsidianPlate.remove(<techreborn:plates:9>);
lazuritePlate.remove(<techreborn:plates:10>);
siliconPlate.remove(<techreborn:plates:11>);

mods.jei.JEI.removeAndHide(<techreborn:plates>);
mods.jei.JEI.removeAndHide(<techreborn:plates:1>);
mods.jei.JEI.removeAndHide(<techreborn:plates:2>);
mods.jei.JEI.removeAndHide(<techreborn:plates:4>);
mods.jei.JEI.removeAndHide(<techreborn:plates:5>);
mods.jei.JEI.removeAndHide(<techreborn:plates:6>);
mods.jei.JEI.removeAndHide(<techreborn:plates:8>);
mods.jei.JEI.removeAndHide(<techreborn:plates:9>);
mods.jei.JEI.removeAndHide(<techreborn:plates:10>);
mods.jei.JEI.removeAndHide(<techreborn:plates:11>);


val woodPlank = <ore:plankWood>;
val woodPlate = <ore:plateWood>;
val iridiumAlloyPlate = <ore:plateIridiumAlloy>;
val iridiumalloyPlate = <ore:plateiridiumAlloy>;
val magnaliumPlate = <ore:plateMagnalium>;
val magnaliumplate = <ore:platemagnalium>;
val advancedAlloyPlate = <ore:plateAdvancedAlloy>;
val advancedalloyPlate = <ore:plateadvancedAlloy>;
val refinedIronPlate = <ore:plateRefinedIron>;
val refinedironPlate = <ore:platerefinedIron>;
val zincPlate = <ore:plateZinc>;
val zincplate = <ore:platezinc>;
val tungstensteelPlate = <ore:plateTungstensteel>;
val tungstensteelplate = <ore:platetungstensteel>;
val tungstenPlate = <ore:plateTungsten>;
val tungstenplate = <ore:platetungsten>;
val titaniumPlate = <ore:plateTitanium>;
val titaniumplate = <ore:platetitanium>;
val tinPlate = <ore:plateTin>;
val tinplate = <ore:platetin>;
val steelPlate = <ore:plateSteel>;
val steelplate = <ore:platesteel>;
val silverPlate = <ore:plateSilver>;
val silverplate = <ore:platesilver>;
val platinumPlate = <ore:platePlatinum>;
val platinumplate = <ore:plateplatinum>;
val nickelPlate = <ore:plateNickel>;
val nickelplate = <ore:platenickel>;
val leadPlate = <ore:plateLead>;
val leadplate = <ore:platelead>;
val iridiumPlate = <ore:plateIridium>;
val iridiumplate = <ore:plateiridium>;
val invarPlate = <ore:plateInvar>;
val invarplate = <ore:plateinvar>;
val electrumPlate = <ore:plateElectrum>;
val electrumplate = <ore:plateelectrum>;
val copperPlate = <ore:plateCopper>;
val copperplate = <ore:platecopper>;
val chromePlate = <ore:plateChrome>;
val chromeplate = <ore:platechrome>;
val bronzePlate = <ore:plateBronze>;
val bronzeplate = <ore:platebronze>;
val brassPlate = <ore:plateBrass>;
val brassplate = <ore:platebrass>;
val aluminiumPlate = <ore:plateAluminum>;
val aluminiumplate = <ore:platealuminum>;
val yellowGarnetPlate = <ore:plateYellowGarnet>;
val yellowgarnetPlate = <ore:plateyellowGarnet>;
val redGarnetPlate = <ore:plateRedGarnet>;
val redgarnetPlate = <ore:plateredGarnet>;
val peridotPlate = <ore:platePeridot>;
val peridotplate = <ore:plateperidot>;
val sapphirePlate = <ore:plateSapphire>;
val sapphireplate = <ore:platesapphire>;
val rubyPlate = <ore:plateRuby>;
val rubyplate = <ore:plateruby>;

woodPlank.remove(<techreborn:plates:3>);
woodPlate.remove(<techreborn:plates:3>);
iridiumAlloyPlate.remove(<techreborn:plates:38>);
iridiumalloyPlate.remove(<techreborn:plates:38>);
magnaliumPlate.remove(<techreborn:plates:37>);
magnaliumplate.remove(<techreborn:plates:37>);
advancedAlloyPlate.remove(<techreborn:plates:36>);
advancedalloyPlate.remove(<techreborn:plates:36>);
refinedIronPlate.remove(<techreborn:plates:35>);
refinedironPlate.remove(<techreborn:plates:35>);
zincPlate.remove(<techreborn:plates:34>);
zincplate.remove(<techreborn:plates:34>);
tungstensteelPlate.remove(<techreborn:plates:33>);
tungstensteelplate.remove(<techreborn:plates:33>);
tungstenPlate.remove(<techreborn:plates:32>);
tungstenplate.remove(<techreborn:plates:32>);
titaniumPlate.remove(<techreborn:plates:31>);
titaniumplate.remove(<techreborn:plates:31>);
tinPlate.remove(<techreborn:plates:30>);
tinplate.remove(<techreborn:plates:30>);
steelPlate.remove(<techreborn:plates:29>);
steelplate.remove(<techreborn:plates:29>);
silverPlate.remove(<techreborn:plates:28>);
silverplate.remove(<techreborn:plates:28>);
platinumPlate.remove(<techreborn:plates:27>);
platinumplate.remove(<techreborn:plates:27>);
nickelPlate.remove(<techreborn:plates:26>);
nickelplate.remove(<techreborn:plates:26>);
leadPlate.remove(<techreborn:plates:25>);
leadplate.remove(<techreborn:plates:25>);
iridiumPlate.remove(<techreborn:plates:24>);
iridiumplate.remove(<techreborn:plates:24>);
invarPlate.remove(<techreborn:plates:23>);
invarplate.remove(<techreborn:plates:23>);
electrumPlate.remove(<techreborn:plates:22>);
electrumplate.remove(<techreborn:plates:22>);
copperPlate.remove(<techreborn:plates:21>);
copperplate.remove(<techreborn:plates:21>);
chromePlate.remove(<techreborn:plates:20>);
chromeplate.remove(<techreborn:plates:20>);
bronzePlate.remove(<techreborn:plates:19>);
bronzeplate.remove(<techreborn:plates:19>);
brassPlate.remove(<techreborn:plates:18>);
brassplate.remove(<techreborn:plates:18>);
aluminiumPlate.remove(<techreborn:plates:17>);
aluminiumplate.remove(<techreborn:plates:17>);
yellowGarnetPlate.remove(<techreborn:plates:16>);
yellowgarnetPlate.remove(<techreborn:plates:16>);
redGarnetPlate.remove(<techreborn:plates:15>);
redgarnetPlate.remove(<techreborn:plates:15>);
peridotPlate.remove(<techreborn:plates:14>);
peridotplate.remove(<techreborn:plates:14>);
sapphirePlate.remove(<techreborn:plates:13>);
sapphireplate.remove(<techreborn:plates:13>);
rubyPlate.remove(<techreborn:plates:12>);
rubyplate.remove(<techreborn:plates:12>);

mods.jei.JEI.removeAndHide(<techreborn:plates:3>);
mods.jei.JEI.removeAndHide(<techreborn:plates:38>);
mods.jei.JEI.removeAndHide(<techreborn:plates:37>);
mods.jei.JEI.removeAndHide(<techreborn:plates:36>);
mods.jei.JEI.removeAndHide(<techreborn:plates:35>);
mods.jei.JEI.removeAndHide(<techreborn:plates:34>);
mods.jei.JEI.removeAndHide(<techreborn:plates:33>);
mods.jei.JEI.removeAndHide(<techreborn:plates:32>);
mods.jei.JEI.removeAndHide(<techreborn:plates:31>);
mods.jei.JEI.removeAndHide(<techreborn:plates:30>);
mods.jei.JEI.removeAndHide(<techreborn:plates:29>);
mods.jei.JEI.removeAndHide(<techreborn:plates:28>);
mods.jei.JEI.removeAndHide(<techreborn:plates:27>);
mods.jei.JEI.removeAndHide(<techreborn:plates:26>);
mods.jei.JEI.removeAndHide(<techreborn:plates:25>);
mods.jei.JEI.removeAndHide(<techreborn:plates:24>);
mods.jei.JEI.removeAndHide(<techreborn:plates:23>);
mods.jei.JEI.removeAndHide(<techreborn:plates:22>);
mods.jei.JEI.removeAndHide(<techreborn:plates:21>);
mods.jei.JEI.removeAndHide(<techreborn:plates:20>);
mods.jei.JEI.removeAndHide(<techreborn:plates:19>);
mods.jei.JEI.removeAndHide(<techreborn:plates:18>);
mods.jei.JEI.removeAndHide(<techreborn:plates:17>);
mods.jei.JEI.removeAndHide(<techreborn:plates:16>);
mods.jei.JEI.removeAndHide(<techreborn:plates:15>);
mods.jei.JEI.removeAndHide(<techreborn:plates:14>);
mods.jei.JEI.removeAndHide(<techreborn:plates:13>);
mods.jei.JEI.removeAndHide(<techreborn:plates:12>);


val plutoniumSmallDust = <ore:dustSmallPlutonium>;
val uraniumSmallDust = <ore:dustSmallUranium>;
val thoriumSmallDust = <ore:dustSmallThorium>;
val iridiumSmallDust = <ore:dustSmallIridium>;
val graniteSmallDust = <ore:dustSmallGranite>;
val dioriteSmallDust = <ore:dustSmallDiorite>;
val andesiteSmallDust = <ore:dustSmallAndesite>;
val glowstoneSmallDust = <ore:dustSmallGlowstone>;
val redstoneSmallDust = <ore:dustSmallRedstone>;
val zincSmallDust = <ore:dustSmallZinc>;
val yellowGarnetSmallDust = <ore:dustSmallYellowGarnet>;
val uvaroviteSmallDust = <ore:dustSmallUvarovite>;
val tungstenSmallDust = <ore:dustSmallTungsten>;
val titaniumSmallDust = <ore:dustSmallTitanium>;
val tinSmallDust = <ore:dustSmallTin>;
val sulfurSmallDust = <ore:dustSmallSulfur>;
val steelSmallDust = <ore:dustSmallSteel>;
val sphaleriteSmallDust = <ore:dustSmallSphalerite>;
val spessartineSmallDust = <ore:dustSmallSpessartine>;
val sodaliteSmallDust = <ore:dustSmallSodalite>;
val silverSmallDust = <ore:dustSmallSilver>;
val sawDustSmallDust = <ore:dustSmallSawDust>;
val sapphireSmallDust = <ore:dustSmallSapphire>;
val saltpeterSmallDust = <ore:dustSmallSaltpeter>;
val rubySmallDust = <ore:dustSmallRuby>;
val redGarnetSmallDust = <ore:dustSmallRedGarnet>;
val pyropeSmallDust = <ore:dustSmallPyrope>;
val pyriteSmallDust = <ore:dustSmallPyrite>;
val platinumSmallDust = <ore:dustSmallPlatinum>;
val phosphorousSmallDust = <ore:dustSmallPhosphorous>;
val peridotSmallDust = <ore:dustSmallPeridot>;
val obsidianSmallDust = <ore:dustSmallObsidian>;
val nickelSmallDust = <ore:dustSmallNickel>;
val netherrackSmallDust = <ore:dustSmallNetherrack>;
val marbleSmallDust = <ore:dustSmallMarble>;
val manganeseSmallDust = <ore:dustSmallManganese>;
val magnesiumSmallDust = <ore:dustSmallMagnesium>;
val leadSmallDust = <ore:dustSmallLead>;
val lazuriteSmallDust = <ore:dustSmallLazurite>;
val ironSmallDust = <ore:dustSmallIron>;
val invarSmallDust = <ore:dustSmallInvar>;
val grossularSmallDust = <ore:dustSmallGrossular>;
val goldSmallDust = <ore:dustSmallGold>;
val galenaSmallDust = <ore:dustSmallGalena>;
val flintSmallDust = <ore:dustSmallFlint>;
val endstoneSmallDust = <ore:dustSmallEndstone>;
val enderPearlSmallDust = <ore:dustSmallEnderPearl>;
val enderEyeSmallDust = <ore:dustSmallEnderEye>;
val emeraldSmallDust = <ore:dustSmallEmerald>;
val electrumSmallDust = <ore:dustSmallElectrum>;
val diamondSmallDust = <ore:dustSmallDiamond>;
val darkAshesSmallDust = <ore:dustSmallDarkAshes>;
val copperSmallDust = <ore:dustSmallCopper>;
val coalSmallDust = <ore:dustSmallCoal>;
val claySmallDust = <ore:dustSmallClay>;
val cinnabarSmallDust = <ore:dustSmallCinnabar>;
val chromeSmallDust = <ore:dustSmallChrome>;
val charcoalSmallDust = <ore:dustSmallCharcoal>;
val calciteSmallDust = <ore:dustSmallCalcite>;
val bronzeSmallDust = <ore:dustSmallBronze>;
val brassSmallDust = <ore:dustSmallBrass>;
val bauxiteSmallDust = <ore:dustSmallBauxite>;
val basaltSmallDust = <ore:dustSmallBasalt>;
val ashesSmallDust = <ore:dustSmallAshes>;
val andraditeSmallDust = <ore:dustSmallAndradite>;
val aluminiumSmallDust = <ore:dustSmallAluminum>;
val almandineSmallDust = <ore:dustSmallAlmandine>;

plutoniumSmallDust.remove(<techreborn:smalldust:69>);
uraniumSmallDust.remove(<techreborn:smalldust:68>);
thoriumSmallDust.remove(<techreborn:smalldust:67>);
iridiumSmallDust.remove(<techreborn:smalldust:66>);
graniteSmallDust.remove(<techreborn:smalldust:65>);
dioriteSmallDust.remove(<techreborn:smalldust:64>);
andesiteSmallDust.remove(<techreborn:smalldust:63>);
glowstoneSmallDust.remove(<techreborn:smalldust:62>);
redstoneSmallDust.remove(<techreborn:smalldust:61>);
zincSmallDust.remove(<techreborn:smalldust:59>);
yellowGarnetSmallDust.remove(<techreborn:smalldust:58>);
uvaroviteSmallDust.remove(<techreborn:smalldust:56>);
tungstenSmallDust.remove(<techreborn:smalldust:55>);
titaniumSmallDust.remove(<techreborn:smalldust:54>);
tinSmallDust.remove(<techreborn:smalldust:53>);
sulfurSmallDust.remove(<techreborn:smalldust:52>);
steelSmallDust.remove(<techreborn:smalldust:51>);
sphaleriteSmallDust.remove(<techreborn:smalldust:50>);
spessartineSmallDust.remove(<techreborn:smalldust:49>);
sodaliteSmallDust.remove(<techreborn:smalldust:48>);
silverSmallDust.remove(<techreborn:smalldust:47>);
sawDustSmallDust.remove(<techreborn:smalldust:46>);
sapphireSmallDust.remove(<techreborn:smalldust:45>);
saltpeterSmallDust.remove(<techreborn:smalldust:44>);
rubySmallDust.remove(<techreborn:smalldust:43>);
redGarnetSmallDust.remove(<techreborn:smalldust:41>);
pyropeSmallDust.remove(<techreborn:smalldust:40>);
pyriteSmallDust.remove(<techreborn:smalldust:39>);
platinumSmallDust.remove(<techreborn:smalldust:38>);
phosphorousSmallDust.remove(<techreborn:smalldust:37>);
peridotSmallDust.remove(<techreborn:smalldust:36>);
obsidianSmallDust.remove(<techreborn:smalldust:35>);
nickelSmallDust.remove(<techreborn:smalldust:34>);
netherrackSmallDust.remove(<techreborn:smalldust:33>);
marbleSmallDust.remove(<techreborn:smalldust:32>);
manganeseSmallDust.remove(<techreborn:smalldust:31>);
magnesiumSmallDust.remove(<techreborn:smalldust:30>);
leadSmallDust.remove(<techreborn:smalldust:29>);
lazuriteSmallDust.remove(<techreborn:smalldust:28>);
ironSmallDust.remove(<techreborn:smalldust:27>);
invarSmallDust.remove(<techreborn:smalldust:26>);
grossularSmallDust.remove(<techreborn:smalldust:25>);
goldSmallDust.remove(<techreborn:smalldust:24>);
galenaSmallDust.remove(<techreborn:smalldust:23>);
flintSmallDust.remove(<techreborn:smalldust:22>);
endstoneSmallDust.remove(<techreborn:smalldust:21>);
enderPearlSmallDust.remove(<techreborn:smalldust:20>);
enderEyeSmallDust.remove(<techreborn:smalldust:19>);
emeraldSmallDust.remove(<techreborn:smalldust:18>);
electrumSmallDust.remove(<techreborn:smalldust:17>);
diamondSmallDust.remove(<techreborn:smalldust:16>);
darkAshesSmallDust.remove(<techreborn:smalldust:15>);
copperSmallDust.remove(<techreborn:smalldust:14>);
coalSmallDust.remove(<techreborn:smalldust:13>);
claySmallDust.remove(<techreborn:smalldust:12>);
cinnabarSmallDust.remove(<techreborn:smalldust:11>);
chromeSmallDust.remove(<techreborn:smalldust:10>);
charcoalSmallDust.remove(<techreborn:smalldust:9>);
calciteSmallDust.remove(<techreborn:smalldust:8>);
bronzeSmallDust.remove(<techreborn:smalldust:7>);
brassSmallDust.remove(<techreborn:smalldust:6>);
bauxiteSmallDust.remove(<techreborn:smalldust:5>);
basaltSmallDust.remove(<techreborn:smalldust:4>);
ashesSmallDust.remove(<techreborn:smalldust:3>);
andraditeSmallDust.remove(<techreborn:smalldust:2>);
aluminiumSmallDust.remove(<techreborn:smalldust:1>);
almandineSmallDust.remove(<techreborn:smalldust>);

mods.jei.JEI.removeAndHide(<techreborn:smalldust:69>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:68>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:67>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:66>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:65>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:64>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:63>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:62>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:61>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:59>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:58>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:56>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:55>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:54>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:53>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:52>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:51>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:50>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:49>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:48>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:47>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:46>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:45>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:44>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:43>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:41>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:40>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:39>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:38>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:37>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:36>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:35>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:34>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:33>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:32>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:31>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:30>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:29>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:28>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:27>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:26>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:25>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:24>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:23>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:22>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:21>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:20>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:19>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:18>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:17>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:16>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:15>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:14>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:13>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:12>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:11>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:10>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:9>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:8>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:7>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:6>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:5>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:4>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:3>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:2>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust:1>);
mods.jei.JEI.removeAndHide(<techreborn:smalldust>);


val ashes = <ore:dustAshes>;
val ash = <ore:dustAsh>;
val woodPulp = <ore:pulpWood>;
val sawdust = <ore:dustSawDust>;

ashes.remove(<techreborn:dust:3>);
ash.remove(<techreborn:dust:3>);
woodPulp.remove(<techreborn:dust:46>);
sawdust.remove(<techreborn:dust:46>);

mods.jei.JEI.removeAndHide(<techreborn:dust:3>);
mods.jei.JEI.removeAndHide(<techreborn:dust:46>);


val thoriumDust = <ore:dustThorium>;
val iridiumDust = <ore:dustIridium>;
val graniteDust = <ore:dustGranite>;
val dioriteDust = <ore:dustDiorite>;
val andesiteDust = <ore:dustAndesite>;
val zincDust = <ore:dustZinc>;
val yellowGarnetDust = <ore:dustYellowGarnet>;
val uvaroviteDust = <ore:dustUvarovite>;
val tungstenDust = <ore:dustTungsten>;
val titaniumDust = <ore:dustTitanium>;
val tinDust = <ore:dustTin>;
val sulfurDust = <ore:dustSulfur>;
val steelDust = <ore:dustSteel>;
val sphaleriteDust = <ore:dustSphalerite>;
val spessartineDust = <ore:dustSpessartine>;
val sodaliteDust = <ore:dustSodalite>;
val silverDust = <ore:dustSilver>;
val plutoniumDust = <ore:dustPlutonium>;
val sapphireDust = <ore:dustSapphire>;
val saltpeterDust = <ore:dustSaltpeter>;
val rubyDust = <ore:dustRuby>;
val redGarnetDust = <ore:dustRedGarnet>;
val pyropeDust = <ore:dustPyrope>;
val pyriteDust = <ore:dustPyrite>;
val platinumDust = <ore:dustPlatinum>;
val phosphorousDust = <ore:dustPhosphorous>;
val peridotDust = <ore:dustPeridot>;
val obsidianDust = <ore:dustObsidian>;
val nickelDust = <ore:dustNickel>;
val netherrackDust = <ore:dustNetherrack>;
val marbleDust = <ore:dustMarble>;
val manganeseDust = <ore:dustManganese>;
val magnesiumDust = <ore:dustMagnesium>;
val leadDust = <ore:dustLead>;
val lazuriteDust = <ore:dustLazurite>;
val ironDust = <ore:dustIron>;
val invarDust = <ore:dustInvar>;
val grossularDust = <ore:dustGrossular>;
val goldDust = <ore:dustGold>;
val galenaDust = <ore:dustGalena>;
val flintDust = <ore:dustFlint>;
val endstoneDust = <ore:dustEndstone>;
val enderPearlDust = <ore:dustEnderPearl>;
val enderEyeDust = <ore:dustEnderEye>;
val emeraldDust = <ore:dustEmerald>;
val electrumDust = <ore:dustElectrum>;
val diamondDust = <ore:dustDiamond>;
val darkAshesDust = <ore:dustDarkAshes>;
val copperDust = <ore:dustCopper>;
val coalDust = <ore:dustCoal>;
val clayDust = <ore:dustClay>;
val cinnabarDust = <ore:dustCinnabar>;
val chromeDust = <ore:dustChrome>;
val charcoalDust = <ore:dustCharcoal>;
val calciteDust = <ore:dustCalcite>;
val bronzeDust = <ore:dustBronze>;
val brassDust = <ore:dustBrass>;
val bauxiteDust = <ore:dustBauxite>;
val basaltDust = <ore:dustBasalt>;
val uraniumDust = <ore:dustUranium>;
val andraditeDust = <ore:dustAndradite>;
val aluminiumDust = <ore:dustAluminum>;
val almandineDust = <ore:dustAlmandine>;

thoriumDust.remove(<techreborn:dust:65>);
iridiumDust.remove(<techreborn:dust:64>);
graniteDust.remove(<techreborn:dust:63>);
dioriteDust.remove(<techreborn:dust:62>);
andesiteDust.remove(<techreborn:dust:61>);
zincDust.remove(<techreborn:dust:59>);
yellowGarnetDust.remove(<techreborn:dust:58>);
uvaroviteDust.remove(<techreborn:dust:56>);
tungstenDust.remove(<techreborn:dust:55>);
titaniumDust.remove(<techreborn:dust:54>);
tinDust.remove(<techreborn:dust:53>);
sulfurDust.remove(<techreborn:dust:52>);
steelDust.remove(<techreborn:dust:51>);
sphaleriteDust.remove(<techreborn:dust:50>);
spessartineDust.remove(<techreborn:dust:49>);
sodaliteDust.remove(<techreborn:dust:48>);
silverDust.remove(<techreborn:dust:47>);
plutoniumDust.remove(<techreborn:dust:67>);
sapphireDust.remove(<techreborn:dust:45>);
saltpeterDust.remove(<techreborn:dust:44>);
rubyDust.remove(<techreborn:dust:43>);
redGarnetDust.remove(<techreborn:dust:41>);
pyropeDust.remove(<techreborn:dust:40>);
pyriteDust.remove(<techreborn:dust:39>);
platinumDust.remove(<techreborn:dust:38>);
phosphorousDust.remove(<techreborn:dust:37>);
peridotDust.remove(<techreborn:dust:36>);
obsidianDust.remove(<techreborn:dust:35>);
nickelDust.remove(<techreborn:dust:34>);
netherrackDust.remove(<techreborn:dust:33>);
marbleDust.remove(<techreborn:dust:32>);
manganeseDust.remove(<techreborn:dust:31>);
magnesiumDust.remove(<techreborn:dust:30>);
leadDust.remove(<techreborn:dust:29>);
lazuriteDust.remove(<techreborn:dust:28>);
ironDust.remove(<techreborn:dust:27>);
invarDust.remove(<techreborn:dust:26>);
grossularDust.remove(<techreborn:dust:25>);
goldDust.remove(<techreborn:dust:24>);
galenaDust.remove(<techreborn:dust:23>);
flintDust.remove(<techreborn:dust:22>);
endstoneDust.remove(<techreborn:dust:21>);
enderPearlDust.remove(<techreborn:dust:20>);
enderEyeDust.remove(<techreborn:dust:19>);
emeraldDust.remove(<techreborn:dust:18>);
electrumDust.remove(<techreborn:dust:17>);
diamondDust.remove(<techreborn:dust:16>);
darkAshesDust.remove(<techreborn:dust:15>);
copperDust.remove(<techreborn:dust:14>);
coalDust.remove(<techreborn:dust:13>);
clayDust.remove(<techreborn:dust:12>);
cinnabarDust.remove(<techreborn:dust:11>);
chromeDust.remove(<techreborn:dust:10>);
charcoalDust.remove(<techreborn:dust:9>);
calciteDust.remove(<techreborn:dust:8>);
bronzeDust.remove(<techreborn:dust:7>);
brassDust.remove(<techreborn:dust:6>);
bauxiteDust.remove(<techreborn:dust:5>);
basaltDust.remove(<techreborn:dust:4>);
uraniumDust.remove(<techreborn:dust:66>);
andraditeDust.remove(<techreborn:dust:2>);
aluminiumDust.remove(<techreborn:dust:1>);
almandineDust.remove(<techreborn:dust>);

mods.jei.JEI.removeAndHide(<techreborn:dust:65>);
mods.jei.JEI.removeAndHide(<techreborn:dust:64>);
mods.jei.JEI.removeAndHide(<techreborn:dust:63>);
mods.jei.JEI.removeAndHide(<techreborn:dust:62>);
mods.jei.JEI.removeAndHide(<techreborn:dust:61>);
mods.jei.JEI.removeAndHide(<techreborn:dust:59>);
mods.jei.JEI.removeAndHide(<techreborn:dust:58>);
mods.jei.JEI.removeAndHide(<techreborn:dust:56>);
mods.jei.JEI.removeAndHide(<techreborn:dust:55>);
mods.jei.JEI.removeAndHide(<techreborn:dust:54>);
mods.jei.JEI.removeAndHide(<techreborn:dust:53>);
mods.jei.JEI.removeAndHide(<techreborn:dust:52>);
mods.jei.JEI.removeAndHide(<techreborn:dust:51>);
mods.jei.JEI.removeAndHide(<techreborn:dust:50>);
mods.jei.JEI.removeAndHide(<techreborn:dust:49>);
mods.jei.JEI.removeAndHide(<techreborn:dust:48>);
mods.jei.JEI.removeAndHide(<techreborn:dust:47>);
mods.jei.JEI.removeAndHide(<techreborn:dust:67>);
mods.jei.JEI.removeAndHide(<techreborn:dust:45>);
mods.jei.JEI.removeAndHide(<techreborn:dust:44>);
mods.jei.JEI.removeAndHide(<techreborn:dust:43>);
mods.jei.JEI.removeAndHide(<techreborn:dust:41>);
mods.jei.JEI.removeAndHide(<techreborn:dust:40>);
mods.jei.JEI.removeAndHide(<techreborn:dust:39>);
mods.jei.JEI.removeAndHide(<techreborn:dust:38>);
mods.jei.JEI.removeAndHide(<techreborn:dust:37>);
mods.jei.JEI.removeAndHide(<techreborn:dust:36>);
mods.jei.JEI.removeAndHide(<techreborn:dust:35>);
mods.jei.JEI.removeAndHide(<techreborn:dust:34>);
mods.jei.JEI.removeAndHide(<techreborn:dust:33>);
mods.jei.JEI.removeAndHide(<techreborn:dust:32>);
mods.jei.JEI.removeAndHide(<techreborn:dust:31>);
mods.jei.JEI.removeAndHide(<techreborn:dust:30>);
mods.jei.JEI.removeAndHide(<techreborn:dust:29>);
mods.jei.JEI.removeAndHide(<techreborn:dust:28>);
mods.jei.JEI.removeAndHide(<techreborn:dust:27>);
mods.jei.JEI.removeAndHide(<techreborn:dust:26>);
mods.jei.JEI.removeAndHide(<techreborn:dust:25>);
mods.jei.JEI.removeAndHide(<techreborn:dust:24>);
mods.jei.JEI.removeAndHide(<techreborn:dust:23>);
mods.jei.JEI.removeAndHide(<techreborn:dust:22>);
mods.jei.JEI.removeAndHide(<techreborn:dust:21>);
mods.jei.JEI.removeAndHide(<techreborn:dust:20>);
mods.jei.JEI.removeAndHide(<techreborn:dust:19>);
mods.jei.JEI.removeAndHide(<techreborn:dust:18>);
mods.jei.JEI.removeAndHide(<techreborn:dust:17>);
mods.jei.JEI.removeAndHide(<techreborn:dust:16>);
mods.jei.JEI.removeAndHide(<techreborn:dust:15>);
mods.jei.JEI.removeAndHide(<techreborn:dust:14>);
mods.jei.JEI.removeAndHide(<techreborn:dust:13>);
mods.jei.JEI.removeAndHide(<techreborn:dust:12>);
mods.jei.JEI.removeAndHide(<techreborn:dust:11>);
mods.jei.JEI.removeAndHide(<techreborn:dust:10>);
mods.jei.JEI.removeAndHide(<techreborn:dust:9>);
mods.jei.JEI.removeAndHide(<techreborn:dust:8>);
mods.jei.JEI.removeAndHide(<techreborn:dust:7>);
mods.jei.JEI.removeAndHide(<techreborn:dust:6>);
mods.jei.JEI.removeAndHide(<techreborn:dust:5>);
mods.jei.JEI.removeAndHide(<techreborn:dust:4>);
mods.jei.JEI.removeAndHide(<techreborn:dust:66>);
mods.jei.JEI.removeAndHide(<techreborn:dust:2>);
mods.jei.JEI.removeAndHide(<techreborn:dust:1>);
mods.jei.JEI.removeAndHide(<techreborn:dust>);


val basicCircuit = <ore:circuitBasic>;
val advancedCircuit = <ore:circuitAdvanced>;
val eliteCircuit = <ore:circuitElite>;
val masterCircuit = <ore:circuitMaster>;

basicCircuit.remove(<techreborn:part:29>);
advancedCircuit.remove(<techreborn:part:30>);
eliteCircuit.remove(<techreborn:part:1>);
masterCircuit.remove(<techreborn:part>);

mods.jei.JEI.removeAndHide(<techreborn:part:29>);
mods.jei.JEI.removeAndHide(<techreborn:part:30>);
mods.jei.JEI.removeAndHide(<techreborn:part:1>);
mods.jei.JEI.removeAndHide(<techreborn:part>);


val tinBlock = <ore:blockTin>;
val copperBlock = <ore:blockCopper>;
val redGarnetBlock = <ore:blockRedGarnet>;
val yellowGarnetBlock = <ore:blockYellowGarnet>;
val peridotBlock = <ore:blockPeridot>;
val sapphireBlock = <ore:blockSapphire>;
val rubyBlock = <ore:blockRuby>;
val tungstensteelBlock = <ore:blockTungstensteel>;
val bronzeBlock = <ore:blockBronze>;
val iridiumBlock = <ore:blockIridium>;
val invarBlock = <ore:blockInvar>;
val nickelBlock = <ore:blockNickel>;
val tungstenBlock = <ore:blockTungsten>;
val platinumBlock = <ore:blockPlatinum>;
val zincBlock = <ore:blockZinc>;
val electrumBlock = <ore:blockElectrum>;
val leadBlock = <ore:blockLead>;
val brassBlock = <ore:blockBrass>;
val steelBlock = <ore:blockSteel>;
val chromeBlock = <ore:blockChrome>;
val titaniumBlock = <ore:blockTitanium>;
val silverBlock = <ore:blockSilver>;
val aluminiumBlock = <ore:blockAluminium>;
val aluminumBlock = <ore:blockAluminum>;

tinBlock.remove(<techreborn:storage2:9>);
copperBlock.remove(<techreborn:storage2:8>);
redGarnetBlock.remove(<techreborn:storage2:7>);
yellowGarnetBlock.remove(<techreborn:storage2:6>);
peridotBlock.remove(<techreborn:storage2:5>);
sapphireBlock.remove(<techreborn:storage2:4>);
rubyBlock.remove(<techreborn:storage2:3>);
tungstensteelBlock.remove(<techreborn:storage2>);
bronzeBlock.remove(<techreborn:storage:14>);
iridiumBlock.remove(<techreborn:storage:13>);
invarBlock.remove(<techreborn:storage:12>);
nickelBlock.remove(<techreborn:storage:11>);
tungstenBlock.remove(<techreborn:storage:10>);
platinumBlock.remove(<techreborn:storage:9>);
zincBlock.remove(<techreborn:storage:8>);
electrumBlock.remove(<techreborn:storage:7>);
leadBlock.remove(<techreborn:storage:6>);
brassBlock.remove(<techreborn:storage:5>);
steelBlock.remove(<techreborn:storage:4>);
chromeBlock.remove(<techreborn:storage:3>);
titaniumBlock.remove(<techreborn:storage:2>);
silverBlock.remove(<techreborn:storage>);
aluminiumBlock.remove(<techreborn:storage:1>);
aluminumBlock.remove(<techreborn:storage:1>);

mods.jei.JEI.removeAndHide(<techreborn:storage2:9>);
mods.jei.JEI.removeAndHide(<techreborn:storage2:8>);
mods.jei.JEI.removeAndHide(<techreborn:storage2:7>);
mods.jei.JEI.removeAndHide(<techreborn:storage2:6>);
mods.jei.JEI.removeAndHide(<techreborn:storage2:5>);
mods.jei.JEI.removeAndHide(<techreborn:storage2:4>);
mods.jei.JEI.removeAndHide(<techreborn:storage2:3>);
mods.jei.JEI.removeAndHide(<techreborn:storage2>);
mods.jei.JEI.removeAndHide(<techreborn:storage:14>);
mods.jei.JEI.removeAndHide(<techreborn:storage:13>);
mods.jei.JEI.removeAndHide(<techreborn:storage:12>);
mods.jei.JEI.removeAndHide(<techreborn:storage:11>);
mods.jei.JEI.removeAndHide(<techreborn:storage:10>);
mods.jei.JEI.removeAndHide(<techreborn:storage:9>);
mods.jei.JEI.removeAndHide(<techreborn:storage:8>);
mods.jei.JEI.removeAndHide(<techreborn:storage:7>);
mods.jei.JEI.removeAndHide(<techreborn:storage:6>);
mods.jei.JEI.removeAndHide(<techreborn:storage:5>);
mods.jei.JEI.removeAndHide(<techreborn:storage:4>);
mods.jei.JEI.removeAndHide(<techreborn:storage:3>);
mods.jei.JEI.removeAndHide(<techreborn:storage:2>);
mods.jei.JEI.removeAndHide(<techreborn:storage>);
mods.jei.JEI.removeAndHide(<techreborn:storage:1>);


val sodaliteOre = <ore:oreSodalite>;
val peridotOre = <ore:orePeridot>;
val sheldoniteOre = <ore:oreSheldonite>;
val tungstenOre = <ore:oreTungsten>;
val sphaleriteOre = <ore:oreSphalerite>;
val cinnabarOre = <ore:oreCinnabar>;
val pyriteOre = <ore:orePyrite>;
val bauxiteOre = <ore:oreBauxite>;
val iridiumOre = <ore:oreIridium>;
val galenaOre = <ore:oreGalena>;
val tinOre = <ore:oreTin>;
val copperOre = <ore:oreCopper>;
val leadOre = <ore:oreLead>;
val silverOre = <ore:oreSilver>;
val sapphireOre = <ore:oreSapphire>;
val rubyOre = <ore:oreRuby>;

sodaliteOre.remove(<techreborn:ore:11>);
peridotOre.remove(<techreborn:ore:10>);
sheldoniteOre.remove(<techreborn:ore:9>);
tungstenOre.remove(<techreborn:ore:8>);
sphaleriteOre.remove(<techreborn:ore:7>);
cinnabarOre.remove(<techreborn:ore:6>);
pyriteOre.remove(<techreborn:ore:5>);
bauxiteOre.remove(<techreborn:ore:4>);
iridiumOre.remove(<techreborn:ore:1>);
galenaOre.remove(<techreborn:ore>);
tinOre.remove(<techreborn:ore2:1>);
copperOre.remove(<techreborn:ore2>);
leadOre.remove(<techreborn:ore:12>);
silverOre.remove(<techreborn:ore:13>);
sapphireOre.remove(<techreborn:ore:3>);
rubyOre.remove(<techreborn:ore:2>);

mods.jei.JEI.removeAndHide(<techreborn:ore:11>);
mods.jei.JEI.removeAndHide(<techreborn:ore:10>);
mods.jei.JEI.removeAndHide(<techreborn:ore:9>);
mods.jei.JEI.removeAndHide(<techreborn:ore:8>);
mods.jei.JEI.removeAndHide(<techreborn:ore:7>);
mods.jei.JEI.removeAndHide(<techreborn:ore:6>);
mods.jei.JEI.removeAndHide(<techreborn:ore:5>);
mods.jei.JEI.removeAndHide(<techreborn:ore:4>);
mods.jei.JEI.removeAndHide(<techreborn:ore:1>);
mods.jei.JEI.removeAndHide(<techreborn:ore>);
mods.jei.JEI.removeAndHide(<techreborn:ore2:1>);
mods.jei.JEI.removeAndHide(<techreborn:ore2>);
mods.jei.JEI.removeAndHide(<techreborn:ore:12>);
mods.jei.JEI.removeAndHide(<techreborn:ore:13>);
mods.jei.JEI.removeAndHide(<techreborn:ore:3>);
mods.jei.JEI.removeAndHide(<techreborn:ore:2>);


mods.jei.JEI.removeAndHide(<techreborn:fluid_replicator>);
mods.jei.JEI.removeAndHide(<techreborn:scrapboxinator>);
mods.jei.JEI.removeAndHide(<techreborn:nuke>);
mods.jei.JEI.removeAndHide(<techreborn:iron_furnace>);
mods.jei.JEI.removeAndHide(<techreborn:pump>);
mods.jei.JEI.removeAndHide(<techreborn:auto_crafting_table>);
mods.jei.JEI.removeAndHide(<techreborn:ev_transformer>);
mods.jei.JEI.removeAndHide(<techreborn:hv_transformer>);
mods.jei.JEI.removeAndHide(<techreborn:mv_transformer>);
mods.jei.JEI.removeAndHide(<techreborn:compressor>);
mods.jei.JEI.removeAndHide(<techreborn:plate_bending_machine>);
mods.jei.JEI.removeAndHide(<techreborn:electric_furnace>);
mods.jei.JEI.removeAndHide(<techreborn:solid_canning_machine>);
mods.jei.JEI.removeAndHide(<techreborn:water_mill>);
mods.jei.JEI.removeAndHide(<techreborn:wind_mill>);
mods.jei.JEI.removeAndHide(<techreborn:wire_mill>);
mods.jei.JEI.removeAndHide(<techreborn:recycler>);
mods.jei.JEI.removeAndHide(<techreborn:distillation_tower>);
mods.jei.JEI.removeAndHide(<techreborn:extractor>);
mods.jei.JEI.removeAndHide(<techreborn:solid_fuel_generator>);
mods.jei.JEI.removeAndHide(<techreborn:grinder>);
mods.jei.JEI.removeAndHide(<techreborn:industrial_sawmill>);
mods.jei.JEI.removeAndHide(<techreborn:vacuum_freezer>);
mods.jei.JEI.removeAndHide(<techreborn:low_voltage_su>);
mods.jei.JEI.removeAndHide(<techreborn:medium_voltage_su>);
mods.jei.JEI.removeAndHide(<techreborn:high_voltage_su>);
mods.jei.JEI.removeAndHide(<techreborn:lv_transformer>);
mods.jei.JEI.removeAndHide(<techreborn:lsu_storage>);
mods.jei.JEI.removeAndHide(<techreborn:lapotronic_su>);
mods.jei.JEI.removeAndHide(<techreborn:adjustable_su>);
mods.jei.JEI.removeAndHide(<techreborn:interdimensional_su>);
mods.jei.JEI.removeAndHide(<techreborn:chemical_reactor>);
mods.jei.JEI.removeAndHide(<techreborn:iron_alloy_furnace>);
mods.jei.JEI.removeAndHide(<techreborn:gas_turbine>);
mods.jei.JEI.removeAndHide(<techreborn:semi_fluid_generator>);
mods.jei.JEI.removeAndHide(<techreborn:magic_energy_absorber>);
mods.jei.JEI.removeAndHide(<techreborn:industrial_electrolyzer>);
mods.jei.JEI.removeAndHide(<techreborn:diesel_generator>);
mods.jei.JEI.removeAndHide(<techreborn:assembling_machine>);
mods.jei.JEI.removeAndHide(<techreborn:magic_energy_converter>);
mods.jei.JEI.removeAndHide(<techreborn:storage2:10>);
mods.jei.JEI.removeAndHide(<techreborn:storage2:2>);
mods.jei.JEI.removeAndHide(<techreborn:storage2:1>);
mods.jei.JEI.removeAndHide(<techreborn:cable:7>);
mods.jei.JEI.removeAndHide(<techreborn:cable:6>);
mods.jei.JEI.removeAndHide(<techreborn:cable:5>);
mods.jei.JEI.removeAndHide(<techreborn:cable:4>);
mods.jei.JEI.removeAndHide(<techreborn:cable:3>);
mods.jei.JEI.removeAndHide(<techreborn:cable:2>);
mods.jei.JEI.removeAndHide(<techreborn:cable:1>);
mods.jei.JEI.removeAndHide(<techreborn:cable>);
mods.jei.JEI.removeAndHide(<techreborn:charge_o_mat>);
mods.jei.JEI.removeAndHide(<techreborn:chunk_loader>);
mods.jei.JEI.removeAndHide(<techreborn:matter_fabricator>);
mods.jei.JEI.removeAndHide(<techreborn:implosion_compressor>);
mods.jei.JEI.removeAndHide(<techreborn:industrial_grinder>);
mods.jei.JEI.removeAndHide(<techreborn:alloy_smelter>);
mods.jei.JEI.removeAndHide(<techreborn:industrial_blast_furnace>.withTag({}));
mods.jei.JEI.removeAndHide(<techreborn:rolling_machine>);
mods.jei.JEI.removeAndHide(<techreborn:industrial_centrifuge>);
mods.jei.JEI.removeAndHide(<techreborn:digital_chest>);
mods.jei.JEI.removeAndHide(<techreborn:creative_quantum_chest>);
mods.jei.JEI.removeAndHide(<techreborn:quantum_chest>);
mods.jei.JEI.removeAndHide(<techreborn:creative_quantum_tank>);
mods.jei.JEI.removeAndHide(<techreborn:quantum_tank>);
mods.jei.JEI.removeAndHide(<techreborn:thermal_generator>);
mods.jei.JEI.removeAndHide(<techreborn:part:4>);
mods.jei.JEI.removeAndHide(<techreborn:part:5>);
mods.jei.JEI.removeAndHide(<techreborn:part:6>);
mods.jei.JEI.removeAndHide(<techreborn:part:13>);
mods.jei.JEI.removeAndHide(<techreborn:part:14>);
mods.jei.JEI.removeAndHide(<techreborn:part:15>);
mods.jei.JEI.removeAndHide(<techreborn:part:21>);
mods.jei.JEI.removeAndHide(<techreborn:part:22>);
mods.jei.JEI.removeAndHide(<techreborn:part:23>);
mods.jei.JEI.removeAndHide(<techreborn:lithiumbatpack>.withTag({energy: 16000000}));
mods.jei.JEI.removeAndHide(<techreborn:lithiumbatpack>.withTag({energy: 0}));
mods.jei.JEI.removeAndHide(<techreborn:lithiumbattery>.withTag({energy: 0}));
mods.jei.JEI.removeAndHide(<techreborn:lithiumbattery>.withTag({energy: 400000}));
mods.jei.JEI.removeAndHide(<techreborn:rebattery>.withTag({energy: 0}));
mods.jei.JEI.removeAndHide(<techreborn:rebattery>.withTag({energy: 40000}));
mods.jei.JEI.removeAndHide(<techreborn:advancedchainsaw>.withTag({energy: 0}));
mods.jei.JEI.removeAndHide(<techreborn:advancedchainsaw>.withTag({energy: 4000000}));
mods.jei.JEI.removeAndHide(<techreborn:advanceddrill>.withTag({energy: 0}));
mods.jei.JEI.removeAndHide(<techreborn:part:33>);
mods.jei.JEI.removeAndHide(<techreborn:part:34>);
mods.jei.JEI.removeAndHide(<techreborn:part:35>);
mods.jei.JEI.removeAndHide(<techreborn:part:45>);
mods.jei.JEI.removeAndHide(<techreborn:part:44>);
mods.jei.JEI.removeAndHide(<techreborn:part:46>);
mods.jei.JEI.removeAndHide(<techreborn:uumatter>);
mods.jei.JEI.removeAndHide(<techreborn:lapotronpack>.withTag({energy: 0}));
mods.jei.JEI.removeAndHide(<techreborn:lapotronpack>.withTag({energy: 400000000}));
mods.jei.JEI.removeAndHide(<techreborn:advanceddrill>.withTag({energy: 4000000}));
mods.jei.JEI.removeAndHide(<techreborn:ironjackhammer>.withTag({energy: 0}));
mods.jei.JEI.removeAndHide(<techreborn:ironjackhammer>.withTag({energy: 4000000}));
mods.jei.JEI.removeAndHide(<techreborn:debug>);
mods.jei.JEI.removeAndHide(<techreborn:diamondchainsaw>.withTag({energy: 0}));
mods.jei.JEI.removeAndHide(<techreborn:diamondchainsaw>.withTag({energy: 400000}));
mods.jei.JEI.removeAndHide(<techreborn:diamonddrill>.withTag({energy: 0}));
mods.jei.JEI.removeAndHide(<techreborn:diamonddrill>.withTag({energy: 400000}));
mods.jei.JEI.removeAndHide(<techreborn:diamondjackhammer>.withTag({energy: 0}));
mods.jei.JEI.removeAndHide(<techreborn:diamondjackhammer>.withTag({energy: 400000}));
mods.jei.JEI.removeAndHide(<techreborn:electrictreetap>.withTag({energy: 0}));
mods.jei.JEI.removeAndHide(<techreborn:electrictreetap>.withTag({energy: 10000}));
mods.jei.JEI.removeAndHide(<techreborn:nanosaber>.withTag({isActive: 0 as byte, energy: 0}));
mods.jei.JEI.removeAndHide(<techreborn:nanosaber>.withTag({isActive: 1 as byte, energy: 640000}));
mods.jei.JEI.removeAndHide(<techreborn:omnitool>.withTag({energy: 0}));
mods.jei.JEI.removeAndHide(<techreborn:omnitool>.withTag({energy: 20000}));
mods.jei.JEI.removeAndHide(<techreborn:rockcutter>.withTag({ench: [{lvl: 1 as short, id: 33 as short}], energy: 0}));
mods.jei.JEI.removeAndHide(<techreborn:rockcutter>.withTag({ench: [{lvl: 1 as short, id: 33 as short}], energy: 400000}));
mods.jei.JEI.removeAndHide(<techreborn:ironchainsaw>.withTag({energy: 0}));
mods.jei.JEI.removeAndHide(<techreborn:ironchainsaw>.withTag({energy: 40000}));
mods.jei.JEI.removeAndHide(<techreborn:irondrill>.withTag({energy: 0}));
mods.jei.JEI.removeAndHide(<techreborn:irondrill>.withTag({energy: 40000}));
mods.jei.JEI.removeAndHide(<techreborn:steeljackhammer>.withTag({energy: 0}));
mods.jei.JEI.removeAndHide(<techreborn:steeljackhammer>.withTag({energy: 40000}));
mods.jei.JEI.removeAndHide(<techreborn:wrench>);
mods.jei.JEI.removeAndHide(<techreborn:singlethoriumfuelrod>.withTag({}));
mods.jei.JEI.removeAndHide(<techreborn:dualthoriumfuelrod>.withTag({}));
mods.jei.JEI.removeAndHide(<techreborn:quadthoriumfuelrod>.withTag({}));
mods.jei.JEI.removeAndHide(<techreborn:depletedsinglethoriumfuelrod>);
mods.jei.JEI.removeAndHide(<techreborn:depleteddualthoriumfuelrod>);
mods.jei.JEI.removeAndHide(<techreborn:depletedquadthoriumfuelrod>);
mods.jei.JEI.removeAndHide(<techreborn:frequencytransmitter>);
mods.jei.JEI.removeAndHide(<techreborn:scrapbox>);
mods.jei.JEI.removeAndHide(<techreborn:techmanuel>);
mods.jei.JEI.removeAndHide(<techreborn:upgrades>);
mods.jei.JEI.removeAndHide(<techreborn:upgrades:1>);
mods.jei.JEI.removeAndHide(<techreborn:upgrades:2>);
mods.jei.JEI.removeAndHide(<techreborn:upgrades:3>);
mods.jei.JEI.removeAndHide(<techreborn:bronzesword>);
mods.jei.JEI.removeAndHide(<techreborn:bronzepickaxe>);
mods.jei.JEI.removeAndHide(<techreborn:bronzespade>);
mods.jei.JEI.removeAndHide(<techreborn:bronzeaxe>);
mods.jei.JEI.removeAndHide(<techreborn:bronzehoe>);
mods.jei.JEI.removeAndHide(<techreborn:bronzehelmet>);
mods.jei.JEI.removeAndHide(<techreborn:bronzechestplate>);
mods.jei.JEI.removeAndHide(<techreborn:bronzeleggings>);
mods.jei.JEI.removeAndHide(<techreborn:bronzeboots>);
mods.jei.JEI.removeAndHide(<techreborn:rubysword>);
mods.jei.JEI.removeAndHide(<techreborn:rubypickaxe>);
mods.jei.JEI.removeAndHide(<techreborn:rubyspade>);
mods.jei.JEI.removeAndHide(<techreborn:rubyaxe>);
mods.jei.JEI.removeAndHide(<techreborn:rubyhoe>);
mods.jei.JEI.removeAndHide(<techreborn:rubyhelmet>);
mods.jei.JEI.removeAndHide(<techreborn:rubychestplate>);
mods.jei.JEI.removeAndHide(<techreborn:rubyleggings>);
mods.jei.JEI.removeAndHide(<techreborn:rubyboots>);
mods.jei.JEI.removeAndHide(<techreborn:sapphiresword>);
mods.jei.JEI.removeAndHide(<techreborn:sapphirepickaxe>);
mods.jei.JEI.removeAndHide(<techreborn:sapphirespade>);
mods.jei.JEI.removeAndHide(<techreborn:sapphireaxe>);
mods.jei.JEI.removeAndHide(<techreborn:sapphirehoe>);
mods.jei.JEI.removeAndHide(<techreborn:sapphirehelmet>);
mods.jei.JEI.removeAndHide(<techreborn:sapphirechestplate>);
mods.jei.JEI.removeAndHide(<techreborn:sapphireboots>);
mods.jei.JEI.removeAndHide(<techreborn:sapphireleggings>);
mods.jei.JEI.removeAndHide(<techreborn:peridotsword>);
mods.jei.JEI.removeAndHide(<techreborn:peridotpickaxe>);
mods.jei.JEI.removeAndHide(<techreborn:peridotspade>);
mods.jei.JEI.removeAndHide(<techreborn:peridotaxe>);
mods.jei.JEI.removeAndHide(<techreborn:peridothoe>);
mods.jei.JEI.removeAndHide(<techreborn:peridothelmet>);
mods.jei.JEI.removeAndHide(<techreborn:peridotchestplate>);
mods.jei.JEI.removeAndHide(<techreborn:peridotleggings>);
mods.jei.JEI.removeAndHide(<techreborn:peridotboots>);
mods.jei.JEI.removeAndHide(<techreborn:techreborn_techreborn.biofuel>);
mods.jei.JEI.removeAndHide(<techreborn:dynamiccell>, false);
mods.jei.JEI.removeAndHide(<techreborn:part:3>);
mods.jei.JEI.removeAndHide(<techreborn:plasma_generator>);
mods.jei.JEI.removeAndHide(<techreborn:computer_cube>);
mods.jei.JEI.removeAndHide(<techreborn:creative_solar_panel>);
mods.jei.JEI.removeAndHide(<techreborn:solar_panel:4>);
mods.jei.JEI.removeAndHide(<techreborn:solar_panel:3>);
mods.jei.JEI.removeAndHide(<techreborn:solar_panel:2>);
mods.jei.JEI.removeAndHide(<techreborn:solar_panel:1>);
mods.jei.JEI.removeAndHide(<techreborn:solar_panel>);
mods.jei.JEI.removeAndHide(<techreborn:lightning_rod>);
mods.jei.JEI.removeAndHide(<techreborn:fusion_control_computer>);